//
//  ShowDetailPresenter.swift
//  VIP
//
//  Created by Sreejith Njamelil on 03.12.18.
//  Copyright (c) 2018 Sreejith Njamelil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowDetailPresentationLogic {
  /* Example:
  func presentSomething(response: ShowDetail.Something.Response)
  */
}

class ShowDetailPresenter: ShowDetailPresentationLogic {
  weak var viewController: ShowDetailDisplayLogic?

  // MARK: Do something
  /* Example:
  func presentSomething(response: ShowDetail.Something.Response) {
    let viewModel = ShowDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
  */
}
