//
//  ShowDetailWorker.swift
//  VIP
//
//  Created by Sreejith Njamelil on 03.12.18.
//  Copyright (c) 2018 Sreejith Njamelil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
// import RxSwift

protocol ShowDetailWorkerLogic: class {
/* Example:
func process(input: Input) -> Output {}
func process(input: Input) -> Single<Output> {}
*/
}

class ShowDetailWorker {
/* Suggested structure:
struct Input { }

struct Output { }

struct Dependencies { }

var dependencies: Dependencies
init(dependencies: Dependencies) {
  self.dependencies = dependencies
}

func process(input: Input) -> Output {}
func process(input: Input) -> Single<Output> {}
*/
}
