//
//  ShowDetailRouter.swift
//  VIP
//
//  Created by Sreejith Njamelil on 03.12.18.
//  Copyright (c) 2018 Sreejith Njamelil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowDetailRoutingLogic {
  /* Example:
  func routeToSomewhere(segue: UIStoryboardSegue?)
  */
}

protocol ShowDetailDataPassing {
  var injectionProvider: (ShowDetailDataStore & ShowDetailModelInjection)? { get }
}

class ShowDetailRouter: NSObject, ShowDetailRoutingLogic, ShowDetailDataPassing {
  weak var viewController: ShowDetailViewController?
  var injectionProvider: (ShowDetailDataStore & ShowDetailModelInjection)?

  // MARK: Routing

  /* Example:
func routeToSomewhere(segue: UIStoryboardSegue?) {
  if let segue = segue {
    let destinationVC = segue.destination as! SomewhereViewController
    var destinationDS = destinationVC.router!.injectionProvider!
    passDataToSomewhere(source: injectionProvider!, destination: &destinationDS)
    passModelToSomewhere(source: injectionProvider!, destination: &destinationDS)
  } else {
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    var destinationDS = destinationVC.router!.injectionProvider!
    passDataToSomewhere(source: injectionProvider!, destination: &destinationDS)
    passModelToSomewhere(source: injectionProvider!, destination: &destinationDS)
    navigateToSomewhere(source: viewController!, destination: destinationVC)
  }
}
  */

  // MARK: Navigation

  /* Example:
  func navigateToSomewhere(source: ShowDetailViewController, destination: SomewhereViewController) {
    source.show(destination, sender: nil)
  }
  */

  // MARK: Passing data

  /* Example:
  func passDataToSomewhere(source: ShowDetailDataStore, destination: inout SomewhereDataStore) {
    destination.name = source.name
  }

  func passModelToSomewhere(source: ShowDetailModelInjection, destination: inout SomewhereModelInjection) {
    destination.name = source.name
  }
  */
}
