//
//  ShowDetailInteractor.swift
//  VIP
//
//  Created by Sreejith Njamelil on 03.12.18.
//  Copyright (c) 2018 Sreejith Njamelil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/** Triggers for business logic visible to the View */
protocol ShowDetailBusinessLogic {
  /* Example:
  func doSomething(request: ShowDetail.Something.Request)
  */
}

/** Property injection protocol */
protocol ShowDetailDataStore {
  /* Example:
  var name: String { get set }
  */
}

/** Model dependency injection protocol */
protocol ShowDetailModelInjection {
  /* Example:
  var modelContainer: ModelContainer { get set }
  */
}

class ShowDetailInteractor: ShowDetailBusinessLogic, ShowDetailDataStore, ShowDetailModelInjection {

  var presenter: ShowDetailPresentationLogic?
  var worker: ShowDetailWorker?
  /* Example:
  var name: String
  var modelContainer: ModelContainer
  */

  /* Example:
  func doSomething(request: ShowDetail.Something.Request) {
    worker = ShowDetailWorker()
    worker?.doSomeWork()

    let response = ShowDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
  */
}
