//
//  GithubReposModels.swift
//  VIP
//
//  Created by Sreejith Njamelil on 14.11.18.
//  Copyright (c) 2018 Sreejith Njamelil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import RxSwift

enum GithubRepos
{
  // MARK: Use cases
  
  enum FetchRepos
  {
    struct Request
    {
      var userId: String?
    }
    struct Response
    {
      var result: [[String: Any]]?
    }
    struct ViewModel
    {
      var repoName: String
      var repoURL: String
    }
  }
}
